[character]
symbol = ""
vicmd_symbol = ""

[cmd_duration]
min_time = 1000
#prefix = "took "

[git-branch]
symbol = " "

#[java]
#symbol = ""
#style = "red"

[python]
symbol = " "
#symbol = ""

[ruby]
symbol = " "

#[package]
#symbol = ""
